### ISSUE TITLE
When we click on the Filter button, it keeps on moving towards the left without stop.

### ISSUE THREAD

**Issue by AlexVentura** [cle61/arctic_admin#22] opened 2017-12-01 22:33 UTC
## Expected Behavior
Admin > Users Screen :: When we click on the Filter button, it expands towards the left.

## Actual Behavior
Admin > Users Screen :: When we click on the Filter button, it keeps on moving towards its left as shown in the Screenshot.

## OS and Browser where Issue was Encountered
- Chrome Version 62.0.3202.94 (Official Build) (64-bit)
- Chrome Canary Version 64.0.3282.0 (Official Build) canary (64-bit)

## Step-by-step Directions to Reproduce Issue
1. Login to the Admin Panel.
2. Click on Users tab.
3. Click on Filter Button available on the right side of the page.
4. Resize the browser window until the minimum size _(with the filter modal opened)_.
5. Close the filter window by clicking once again in the filter button.
6. Maximize the browser window until the maximum size and you'll see the filter bug as shown in the Picture 1.
7. Click on the filter button again and again and again... and you could see how it goes and goes and goes towards the left side until you can not click on it anymore as shown in the Picture 2.

Can you get it fixed soon?

Picture 1
<img width="1552" alt="screen shot 2017-12-01 at 15 53 48" src="https://user-images.githubusercontent.com/13169164/33505200-0ce50f98-d6b0-11e7-9237-ef0ac6d5bda3.png">

Picture 2
![l8swex1eui](https://user-images.githubusercontent.com/13169164/33506340-19eac9d0-d6b5-11e7-96f5-b5f32ce1482c.gif)

**Comment by haariiii** [comment] 2017-12-20 07:47
please fix this, the filter can't close

**Comment by wasifhossain** [comment] 2018-01-21 23:13
The demo site might still have the issue remaining but after testing it on my project using the latest gem version (1.4.2) on chromium (64.0.3282.85), I can confirm that the issue is now resolved!

@cle61 can you please close this issue if you consider it right so?

**Comment by AlexVentura** [comment] 2018-03-08 15:27
Actually I have made a brand-new app using `ActiveAdmin: >= 1.1.0, < 2.0` and `arctic_admin (1.4.3)` and `devise (4.4.1)` and it still having the issue!

@wasifhossain  I'm pretty sure it have not been fixed!

**Closed** 2018-03-11 17:03 UTC
